### ISSUE TITLE
Enums with arbitrary types

### ISSUE THREAD

**Issue by 2torus** [near/borsh-py#11]
Thank you for the great project!
I wanted to create an enum which had a `Vec` as a parameter:
```
from borsh_construct import Enum, Vec, U8
EnumWithVec = Enum(
    "VecTag" / Vec(U8),
    enum_name="Instruction"
)
```
This gives me `ValueError: Unrecognized variant type: <class 'construct.core.FocusedSeq'>`. 
In Rust, this is a perfectly acceptable type.
I'm willing to implement such a feature myself, especially if somebody can guide me with an architectural plan.

**Comment by frol** [comment]
@kevinheavey Could you, please, take a look?

**Comment by kevinheavey** [comment]
@2torus you can just wrap it in a TupleStruct:

```python
from borsh_construct import Enum, Vec, U8, TupleStruct
EnumWithVec = Enum(
    "VecTag" / TupleStruct(Vec(U8)),
    enum_name="Instruction"
)
```

This is what it's like in Rust too: every enum variant is a struct (either a unit struct, tuple struct or C-like struct).

Though I will concede that writing these enums in Rust is a lot more elegant. I'm trying to think now if it would be good for borsh-construct to automatically wrap things in a TupleStruct when needed so that your initial code would just work.

**Comment by kevinheavey** [comment]
> I'm trying to think now if it would be good for borsh-construct to automatically wrap things in a TupleStruct when needed

My conclusion is that this would be bad as it enables a lot of accidents
